###
GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "fghj",
    "username": "fefe",
    "email": "efe@fegv.com",
    "password": "tyyby",
    "phone": "0694930209"
}