###
GET http://localhost:5000/screen/1/hardSkills


###
POST http://localhost:5000/screen/1/hardSkills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYyNjE2OTg1MH0.buBApOxUWdgI799EbnicvhGKEqh7y9XrBpGahQr-14I

{
    "number":  "1",
    "hardSkillsName":"Project"
}

###
POST http://localhost:5000/screen/1/hardSkills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYyNjE2OTg1MH0.buBApOxUWdgI799EbnicvhGKEqh7y9XrBpGahQr-14I

{
    "number":  "2",
    "hardSkillsName":"Excel"
}

###
POST http://localhost:5000/screen/1/hardSkills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYyNjE2OTg1MH0.buBApOxUWdgI799EbnicvhGKEqh7y9XrBpGahQr-14I


{
    "number":  "3",
    "hardSkillsName":"Accounts"
}


###
DELETE http://localhost:5000/screen/1/hardSkills/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYyNjE2OTg1MH0.buBApOxUWdgI799EbnicvhGKEqh7y9XrBpGahQr-14I
