###
GET http://localhost:5000/screen/1/hardSkills


###
POST http://localhost:5000/screen/1/hardSkills
Content-Type: application/json

{
    "number":  "1",
    "hardSkillsName":"Project"
}

###
POST http://localhost:5000/screen/1/hardSkills
Content-Type: application/json

{
    "number":  "2",
    "hardSkillsName":"Excel"
}

###
POST http://localhost:5000/screen/1/hardSkills
Content-Type: application/json

{
    "number":  "3",
    "hardSkillsName":"Accounts"
}


###
DELETE http://localhost:5000/screen/1/hardSkills/1