
###
GET http://localhost:5000/screen/1/langues


###
POST http://localhost:5000/screen/1/langues
Content-Type: application/json

{
    "number":  "1",
    "langueName":"Dutch"
}

###
POST http://localhost:5000/screen/1/langues
Content-Type: application/json

{
    "number":  "2",
    "langueName":"French"
}

###
POST http://localhost:5000/screen/1/langues
Content-Type: application/json

{
    "number":  "3",
    "langueName":"English"
}

###
DELETE http://localhost:5000/screen/1/langues/1