###
GET http://localhost:5000/screen

###
GET http://localhost:5000/screen/1

###
POST http://localhost:5000/screen
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYyNjE2OTg1MH0.buBApOxUWdgI799EbnicvhGKEqh7y9XrBpGahQr-14I

{

    "name": "Calvin Hyacinth",
    "username": "chyacin317",
    "telephone": "0781843810"

}

###
POST http://localhost:5000/screen
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTYyNTgyMDgzN30.nC7zeaH20h8nLkBgDxEabRqjZ0EECNivOVo4LLjUI0c

{

    "name": "Thomas Dietrich",
    "username": "tomtom",
    "telephone": "0755581045"

}

###
PUT http://localhost:5000/screen/1
Content-Type: application/json

{

    "username": "ch"

}


###
DELETE http://localhost:5000/screen/1

