###
GET http://localhost:5000/screen

###
GET http://localhost:5000/screen/1

###
POST http://localhost:5000/screen
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTYyNTY1OTU5NH0.mrEoOoKY_UtmM4JDmYWTDQ_XcOrpHZ2SbIuPbaG1Xr4

{

    "name": "Calvin Hyacinth",
    "username": "chyacin317",
    "telephone": "0781843810"

}

###
POST http://localhost:5000/screen
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTYyNTY1MTc4M30.h7dL-2p2Vltg5aPOu6lmsnpTMTq8k5R6c1vaBQWXyf8

{

    "name": "Thomas Dietrich",
    "username": "tomtom",
    "telephone": "0755581045"

}

###
PUT http://localhost:5000/screen/1
Content-Type: application/json

{

    "username": "ch"

}


###
DELETE http://localhost:5000/screen/1

