###
GET http://localhost:5000/screen/2/softskills

###
POST http://localhost:5000/screen/1/softskills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTYyNTgyMDgzN30.nC7zeaH20h8nLkBgDxEabRqjZ0EECNivOVo4LLjUI0c

{
    "number":  "1",
    "softskills":"communication"
}

###
POST http://localhost:5000/screen/1/softskills
Content-Type: application/json

{
    "number":  "2",
    "softskills":"cooperation"
}

###
POST http://localhost:5000/screen/1/softskills
Content-Type: application/json

{
    "number":  "3",
    "softskills":"creatitive"
}

###
DELETE http://localhost:5000/screen/1/softskills/1