###
GET http://localhost:5000/screen/2/softskills

###
POST http://localhost:5000/screen/2/softskills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTYyNjE2OTc3Nn0.6ysLXSEpHINIv3vewt5kpsk6PXj6NUbSuaP0PiyrJLA


{
    "softskills":"communication"
}

###
POST http://localhost:5000/screen/1/softskills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYyNjE2OTg1MH0.buBApOxUWdgI799EbnicvhGKEqh7y9XrBpGahQr-14I

{
    "number":  "2",
    "softskills":"cooperation"
}

###
POST http://localhost:5000/screen/1/softskills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYyNjE2OTg1MH0.buBApOxUWdgI799EbnicvhGKEqh7y9XrBpGahQr-14I

{
    "number":  "3",
    "softskills":"creatitive"
}

###
DELETE http://localhost:5000/screen/1/softskills/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTYyNjE2OTg1MH0.buBApOxUWdgI799EbnicvhGKEqh7y9XrBpGahQr-14I

