###
GET http://localhost:5000/values

###
GET http://localhost:5000/values/6

###
GET http://localhost:5000/screen/1/values

###
POST http://localhost:5000/screen/1/values
Content-Type: application/json

{
    "value_id":  "2"
}