###
GET http://localhost:5000/screen/1/values

###
POST http://localhost:5000/screen/1/values
Content-Type: application/json

{

    "number":  "1",
    "valueName": "hard working"

}


###
POST http://localhost:5000/screen/1/values
Content-Type: application/json

{

    "number":  "2",
    "valueName": "team spirit"
    
}

###
POST http://localhost:5000/screen/1/values
Content-Type: application/json

{

    "number":  "3",
    "valueName": "values"
    
}